export const DeveloperProfiles = [
    {
        name: 'Uly',
        skills: ['skilled','stuff','things'],
        title: 'General Manager',
        profile: 'This is some profile text.',
        avatar: require('./images/uly.png'),
    },
    {
        name: 'Calum',
        skills: ['skilled','stuff','things'],
        title: 'Solution Architect',
        profile: 'This is some profile text.',
        avatar: require('./images/calum.png'),
    },
    {
        name: 'Jack',
        skills: ['skilled','stuff','things'],
        title: 'Software Architect',
        profile: 'This is some profile text.',
        avatar: require('./images/jack.png'),
    },
    {
        name: 'Liam',
        skills: ['skilled','stuff','things'],
        title: 'Solution Architect',
        profile: 'This is some profile text.',
        avatar: require('./images/liam.png'),
    },
    {
        name: 'Matt',
        skills: ['skilled','stuff','things'],
        title: 'Solution Architect',
        profile: 'This is some profile text.',
        avatar: require('./images/matt.png'),
    },
    {
        name: 'Adam',
        skills: ['skilled','stuff','things'],
        title: 'Chief Architect',
        profile: 'This is some profile text.',
        avatar: require('./images/adam.png'),
    },
    {
        name: 'Jean',
        skills: ['skilled','stuff','things'],
        title: 'Solution Architect',
        profile: 'This is some profile text.',
        avatar: require('./images/jean.png'),
    },
];