export const AuthTypes = {
    SIGN_IN_ATTEMPT: 'SIGN_IN_ATTEMPT',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    SIGN_OUT: 'SIGN_OUT'
}

export const ApiTypes = {
    GET_WEATHER_FORECAST_ATTEMPT: 'GET_WEATHER_FORECAST_ATTEMPT',
    GET_WEATHER_FORECAST_SUCCESS: 'GET_WEATHER_FORECAST_SUCCESS',
    GET_WEATHER_FORECAST_FAILURE: 'GET_WEATHER_FORECAST_FAILURE'
}