using System.Text.RegularExpressions;
using SSW.Rewards.DevTool.Core;

namespace SSW.Rewards.DevTool.Apps;

// Mobile app: git-ignored src/MobileUI/Constants.LocalDev.cs (LocalApiBaseUrl /
// LocalAuthorityUri). This file is also the canonical current-state store the CLI
// reads back to preserve whichever dimension a command isn't changing.
public static class MobileConfig
{
    public static bool Exists(RepoPaths paths) => File.Exists(paths.MobileLocalFile);

    public static TargetState ReadCurrent(RepoPaths paths)
    {
        var api = Presets.DefaultApi;
        var authority = Presets.DefaultAuthority;
        if (File.Exists(paths.MobileLocalFile))
        {
            var text = File.ReadAllText(paths.MobileLocalFile);
            api = Match(text, "LocalApiBaseUrl") ?? api;
            authority = Match(text, "LocalAuthorityUri") ?? authority;
        }
        return new TargetState(api, authority);

        static string? Match(string text, string name)
        {
            var m = Regex.Match(text, name + @"\s*=\s*""([^""]*)""");
            return m.Success ? m.Groups[1].Value : null;
        }
    }

    public static void Write(RepoPaths paths, TargetState state)
    {
        File.WriteAllText(paths.MobileLocalFile,
$$"""
// <auto-generated> rewards-dev — local dev overrides. GIT-IGNORED. Do not commit.
namespace SSW.Rewards;

public static partial class Constants
{
    private const string LocalApiBaseUrl = "{{state.Api}}";
    private const string LocalAuthorityUri = "{{state.Authority}}";
}
""");
    }

    public static void Delete(RepoPaths paths)
    {
        if (File.Exists(paths.MobileLocalFile)) File.Delete(paths.MobileLocalFile);
    }
}
