global using AutoMapper;
global using FluentValidation;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using SSW.Rewards.Application.Common.Constants;
global using SSW.Rewards.Application.Common.Extensions;
global using SSW.Rewards.Application.Common.Interfaces;
global using SSW.Rewards.Domain.Entities;
global using SSW.Rewards.Enums;
