name: Build and Test (Automation)

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  admin:
    uses: ./.github/workflows/ci.yml
    with:
      project_path: src/AdminUI/AdminUI.csproj

  api:
    uses: ./.github/workflows/ci.yml
    with:
      project_path: src/WebAPI/WebAPI.csproj

  mobile:
    uses: ./.github/workflows/ci.yml
    with:
      project_path: src/MobileUI/MobileUI.csproj
      test_mobile: true

  mobile-core-unit:
    uses: ./.github/workflows/ci.yml
    with:
      project_path: tests/MobileUI.Core.UnitTests/MobileUI.Core.UnitTests.csproj

  mobile-core-integration:
    uses: ./.github/workflows/ci.yml
    with:
      project_path: tests/MobileUI.Core.IntegrationTests/MobileUI.Core.IntegrationTests.csproj
